#!/bin/sh
# Regenerates docs/DELETION-TEST.md by running the suite from a fresh clone.
# Not part of the shipped toolchain; it exists so the transcript in that file is
# reproducible rather than asserted.

set -u
SRC=${1:-.}
# Absolute before the cd below, or the transcript lands in the temp dir we delete.
case "$SRC" in
    /*) ;;
    *) SRC=$(pwd)/$SRC ;;
esac
DEST="$SRC/docs/DELETION-TEST.md"
CLONE=$(mktemp -d)
trap 'rm -rf "$CLONE"' EXIT INT TERM

git clone -q "$SRC" "$CLONE/vault" 2>/dev/null || { printf 'clone failed\n' >&2; exit 1; }
cd "$CLONE/vault" || exit 1

D=$(date -u +%Y-%m-%d)

{
  printf '# The deletion test\n\n'
  printf 'This file is a **transcript, not a claim**. It was generated by\n'
  printf '`tests/regen-deletion-test.sh`, which clones this repository into a\n'
  printf 'temporary directory and runs the suite from the clean checkout. If you\n'
  printf 're-run it and get a different result, the file was hand-edited.\n\n'
  printf -- '- **Date:** %s\n' "$D"
  printf -- '- **Shell:** %s\n' "$("${SHELL:-sh}" --version 2>/dev/null | head -1 || echo 'sh')"
  printf -- '- **awk:** %s\n' "$(awk --version 2>/dev/null | head -1 || awk -W version 2>&1 | head -1)"
  printf '\n---\n\n## What the deletion test does\n\n'
  printf 'For each example vault it:\n\n'
  printf '1. copies every `.md` file to a temporary directory,\n'
  printf '2. **deletes every non-markdown file**, by construction — only markdown\n'
  printf '   is ever copied,\n'
  printf '3. re-runs the full lint over the stripped copy,\n'
  printf '4. fails if the result is not clean.\n\n'
  printf '## What it proves\n\n'
  printf 'That the laws, the schema, the scheduler state and the whole vocabulary\n'
  printf 'survive the removal of every tool. The vault is still readable with\n'
  printf '`cat`, still greppable, still writable by hand.\n\n'
  printf '## What it does NOT prove\n\n'
  printf 'Read this part; a test that only advertises its strengths is marketing.\n\n'
  printf -- '- **It does not prove the tools are unnecessary.** `bin/` is optional in\n'
  printf -- '  the sense that the vault works without it, not in the sense that the\n'
  printf -- '  scheduler is nice to have. FSRS would schedule better.\n'
  printf -- '- **It does not prove portability of format.** The schema is a\n'
  printf -- '  documented convention in this repository. Markdown itself is portable;\n'
  printf -- '  `type: proof` is not a standard, and a future editor will not know it.\n'
  printf -- '- **It does not prove you learned anything.** It proves the record is\n'
  printf -- '  intact and the laws are enforced. Whether a claim in it is true and\n'
  printf -- '  retained is a question about the reader, which no linter can answer.\n'
  printf -- '- **It does not cover the git history**, which is a second durable store\n'
  printf -- '  this project leans on and does not test.\n'
  printf -- '- **A passing run is a floor, not a ceiling.** It shows the laws are\n'
  printf -- '  checked. It does not show the laws are the right laws.\n\n'
  printf -- '---\n\n## Transcript\n\n```console\n'
  printf '$ git clone <repo> /tmp/vault && cd /tmp/vault\n\n'
  printf '$ sh tests/harness.sh\n'
  sh tests/harness.sh 2>&1 | tail -3
  printf 'exit %s\n\n' "$([ $? -eq 0 ] && echo 0 || echo 1)"
  printf '$ sh tests/lint-tests.sh\n'
  sh tests/lint-tests.sh 2>&1 | tail -3
  printf 'exit %s\n\n' "$([ $? -eq 0 ] && echo 0 || echo 1)"
  printf '$ bin/g-lint --repo-root . --deletion-test\n'
  bin/g-lint --repo-root . --deletion-test 2>&1
  printf 'exit %s\n' "$([ $? -eq 0 ] && echo 0 || echo 1)"
  printf '```\n'
} > "$DEST"

printf '%s\n' "$DEST"
